import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import axios from "axios";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [email , setEmail] = useState();
  const [feedBack, setFeedBack] = useState();
  const [feedBacks , setFeedBacks] = useState([]);

  const handleSubmit = async  (event) => {
    event.preventDefault();

    const {data} = await axios.post("http://localhost:3000/api/feedback", {
      email , feedBack
    });
  }
  const getDataFromServer = async () => {
    const {data} = await axios.get("http://localhost:3000/api/feedback");
    setFeedBacks(data.arrayOfFeedBack);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main > 
          <form onSubmit={handleSubmit}>
              <h2>Send FeedBack</h2>
              <div className=''>
                <label>Email : </label>
                <input value={email}  onChange={e => setEmail(e.target.value)} type='email' placeholder='Enter email'  />
              </div>
              <div className=''>
                <label>FeedBack : </label>
                <input value={feedBack}  onChange={e => setFeedBack(e.target.value)} type='text' placeholder='Enter FeedBack'  />
              </div>
              <button type='submit'>Send FeedBack</button>
          </form>
      </main>

      <section>
        <button onClick={getDataFromServer}>Load feedBacks</button>
        <main>
            {feedBacks.map(feed => <li>{feed.feedBack}</li>)}
        </main>
      </section>
    </>
  )
}
